"""pa_cli.review_adjudicate — Dual-agent review & adjudication loop.

Per ROADMAP [P3-33]:
  Connects the 5-role academic reviewer panel with Paper Agent's M2/M5 adjudication schema,
  evaluating drafted literature review sections against strict peer-review criteria:
  (1) Journal-Fit Reviewer (scope, academic framing, structural balance, research gap)
  (2) Methodology & Identification Reviewer (causal identification rigor, overclaim detection)
  (3) Domain Literature Reviewer (citation coverage, seminal balance, citation density)
  (4) Boundary Conditions Reviewer (generalizability, institutional qualifiers, moderators)
  (5) Devil's Advocate Reviewer (logic fallacies, cherry-picking, confirmation bias, counter-arguments)
  (6) Editorial Adjudication & Prioritized Revision Roadmap (Accept / Minor / Major / Reject)
  (7) Drafter Revision Loop (--revise): Automated draft refinement and "Response to Reviewers" letter.

Global Rule audit:
  100% offline-first execution; pure Python heuristic NLP analysis;
  zero cloud dependencies; zero external API cost; Windows safe ASCII fallback.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

log = logging.getLogger(__name__)


# ==============================================================================
# Data Structures
# ==============================================================================

@dataclass
class CritiqueItem:
    """A specific issue or constructive comment raised by a reviewer."""
    severity: str  # 'CRITICAL', 'MAJOR', 'MINOR', 'PRAISE'
    category: str  # 'identification', 'citation', 'logic', 'framing', 'boundary', 'style'
    sentence_anchor: str  # The specific text passage or section triggering the comment
    critique: str  # Detailed referee explanation
    suggested_remedy: str  # Actionable advice on how to address the issue
    resolved_in_revision: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ReviewerReport:
    """Evaluation report generated by one of the 5 reviewer panel seats."""
    seat_id: str  # 'eic', 'methodology', 'domain', 'perspective', 'devils_advocate'
    seat_name: str  # Human-readable seat title
    score: float  # 1.0 to 10.0 scale
    strengths: list[str] = field(default_factory=list)
    critiques: list[CritiqueItem] = field(default_factory=list)
    summary_verdict: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "seat_id": self.seat_id,
            "seat_name": self.seat_name,
            "score": round(self.score, 1),
            "strengths": self.strengths,
            "critiques": [c.to_dict() for c in self.critiques],
            "summary_verdict": self.summary_verdict,
        }


@dataclass
class RoadmapItem:
    """A prioritized task in the editorial revision roadmap."""
    priority: str  # 'MUST-ADDRESS', 'RECOMMENDED', 'POLISH'
    source_seats: list[str]
    issue: str
    action_required: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class AdjudicationDecision:
    """The synthesized editorial decision and arbitration across all 5 seats."""
    composite_score: float  # 1.0 - 10.0
    editorial_decision: str  # 'ACCEPT', 'MINOR_REVISION', 'MAJOR_REVISION', 'REJECT_AND_RESUBMIT'
    target_venue_tier: str  # 'top', 'field_top', 'general', 'working_paper'
    reviewer_reports: list[ReviewerReport] = field(default_factory=list)
    consensus_strengths: list[str] = field(default_factory=list)
    consensus_weaknesses: list[str] = field(default_factory=list)
    arbitrated_disagreements: list[str] = field(default_factory=list)
    da_critical_count: int = 0
    revision_roadmap: list[RoadmapItem] = field(default_factory=list)
    editorial_letter: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "composite_score": round(self.composite_score, 2),
            "editorial_decision": self.editorial_decision,
            "target_venue_tier": self.target_venue_tier,
            "reviewer_reports": [r.to_dict() for r in self.reviewer_reports],
            "consensus_strengths": self.consensus_strengths,
            "consensus_weaknesses": self.consensus_weaknesses,
            "arbitrated_disagreements": self.arbitrated_disagreements,
            "da_critical_count": self.da_critical_count,
            "revision_roadmap": [item.to_dict() for item in self.revision_roadmap],
            "editorial_letter": self.editorial_letter,
        }


@dataclass
class DualAgentPackage:
    """Complete output package containing first-round review, revised draft, and response letter."""
    initial_adjudication: AdjudicationDecision
    revised_text: Optional[str] = None
    response_to_reviewers: Optional[str] = None
    post_revision_adjudication: Optional[AdjudicationDecision] = None
    score_delta: float = 0.0

    @property
    def has_revision(self) -> bool:
        return self.revised_text is not None

    def to_dict(self) -> dict[str, Any]:
        return {
            "initial_adjudication": self.initial_adjudication.to_dict(),
            "has_revision": self.has_revision,
            "score_delta": round(self.score_delta, 2),
            "revised_text": self.revised_text,
            "response_to_reviewers": self.response_to_reviewers,
            "post_revision_adjudication": self.post_revision_adjudication.to_dict() if self.post_revision_adjudication else None,
        }



# ==============================================================================
# Heuristic NLP Extraction & Analysis Helpers
# ==============================================================================

def split_sentences(text: str) -> list[str]:
    """Split text into sentences while protecting citations and academic abbreviations."""
    protected = text
    subs = {
        "e.g.": "__EG__",
        "i.e.": "__IE__",
        "et al.": "__ETAL__",
        "vs.": "__VS__",
        "cf.": "__CF__",
        "p.": "__PG__",
        "pp.": "__PPG__",
        "vol.": "__VOL__",
        "no.": "__NUM__",
    }
    for k, v in subs.items():
        protected = re.sub(re.escape(k), v, protected, flags=re.IGNORECASE)

    raw_sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9\"'\[@])", protected)
    sentences = []
    for s in raw_sentences:
        clean = s.strip()
        for k, v in subs.items():
            clean = clean.replace(v, k)
        if len(clean) > 5:
            sentences.append(clean)
    return sentences


def count_citations(text: str) -> int:
    """Count explicit academic citations in text."""
    citeproc = len(re.findall(r"\[@[^\]]+\]", text))
    latex = len(re.findall(r"\\(?:cite|citep|citet|autocite)\{[^\}]+\}", text))
    inline_yr = len(re.findall(r"\b[A-Z][a-zA-Z\s]{1,25}\s*(?:et\s*al\.\s*)?\((?:19|20)\d{2}\)", text))
    return citeproc + latex + inline_yr


def extract_paragraphs(text: str) -> list[str]:
    """Extract non-empty paragraphs from markdown text."""
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    return [p for p in paras if not p.startswith("#")]


# Causal overclaim verb pattern: unhedged strong assertion without identification qualifier
CAUSAL_OVERCLAIM_PAT = re.compile(
    r"\b(?:proves?\s+that|definitively\s+(?:shows?|demonstrates?)|unquestionably\s+causes?|directly\s+establishes\s+causality|guarantees?\s+that)\b",
    re.IGNORECASE,
)

# Identification strategy keywords indicating methodological rigor
IDENTIFICATION_PAT = re.compile(
    r"\b(?:difference[- ]in[- ]differences|DID|two[- ]way\s+fixed\s+effects|TWFE|instrumental\s+variable|IV|2SLS|regression\s+discontinuity|RDD|synthetic\s+control|exogenous\s+shock|natural\s+experiment|parallel\s+trends?|exclusion\s+restriction)\b",
    re.IGNORECASE,
)

# Boundary condition and heterogeneity keywords
BOUNDARY_PAT = re.compile(
    r"\b(?:heterogeneity|boundary\s+condition|cross[- ]sectional\s+variation|moderating\s+effect|conditional\s+on|subsample|SOE[s]?|non[- ]SOE[s]?|firm\s+size|institutional\s+context|emerging\s+markets?|financial\s+constraints?)\b",
    re.IGNORECASE,
)

# Counter-argument and empirical tension keywords
TENSION_PAT = re.compile(
    r"\b(?:however|in\s+contrast|contrary\s+to|conversely|divergent\s+findings|mixed\s+evidence|competing\s+hypotheses|unresolved\s+debate|conflicting\s+results)\b",
    re.IGNORECASE,
)


# ==============================================================================
# Five Reviewer Panel Seats Evaluators
# ==============================================================================

def review_journal_fit(text: str, venue_tier: str = "field_top") -> ReviewerReport:
    """Seat 1: Journal-Fit Reviewer. Evaluates scope, framing, and research gap."""
    critiques: list[CritiqueItem] = []
    strengths: list[str] = []
    base_score = 8.5

    # 1. Structure check: Does it have thematic sections or just a wall of text?
    headers = re.findall(r"^#{1,4}\s+(.+)$", text, re.MULTILINE)
    if len(headers) >= 3:
        strengths.append(f"Well-structured thematic presentation across {len(headers)} subsections.")
    else:
        base_score -= 1.5
        critiques.append(CritiqueItem(
            severity="MAJOR",
            category="framing",
            sentence_anchor="Manuscript structural layout",
            critique="The literature review lacks clear thematic subsections (e.g., Theoretical Foundations, Core Empirical Debates, Gaps). It reads like an unstructured sequence of summaries.",
            suggested_remedy="Divide the review into structured thematic sections: Theoretical Foundations, Empirical Identification, and Research Gaps.",
        ))

    # 2. Research gap check: Does it articulate what remains unsolved?
    has_gap = bool(re.search(r"\b(?:research\s+gap|unresolved|remains\s+unclear|open\s+question|unaddressed|future\s+inquiry)\b", text, re.I))
    if has_gap:
        strengths.append("Clearly demarcates existing empirical literature from unaddressed research gaps.")
    else:
        base_score -= 1.2
        critiques.append(CritiqueItem(
            severity="MAJOR",
            category="framing",
            sentence_anchor="Concluding paragraphs",
            critique="The review fails to explicitly articulate an unresolved research gap. A high-tier journal requires authors to explain what literature has NOT established.",
            suggested_remedy="Conclude the review with an explicit 'Unresolved Tensions & Research Gaps' subsection motivating the study's incremental contribution.",
        ))

    # 3. Tone and formality check
    informal = re.findall(r"\b(?:obviously|everyone\s+knows|a\s+lot\s+of|lots\s+of|super\s+important|huge\s+impact)\b", text, re.I)
    if informal:
        base_score -= 0.8
        critiques.append(CritiqueItem(
            severity="MINOR",
            category="style",
            sentence_anchor=f"Informal phrase: '{informal[0]}'",
            critique=f"Colloquial terminology detected ('{informal[0]}'). Academic journals expect formal scholarly rhetoric.",
            suggested_remedy="Replace informal vernacular with objective scholarly terminology (e.g. 'substantial effect', 'widely acknowledged').",
        ))
    else:
        strengths.append("Professional scholarly tone and academic register maintained throughout.")

    # Venue tier expectations
    if venue_tier == "top" and base_score > 7.0:
        base_score -= 0.5  # Top tier journals apply stricter standards

    score = max(1.0, min(10.0, base_score))
    verdict = "Acceptable journal framing" if score >= 7.0 else "Needs clearer scholarly motivation and structure"
    return ReviewerReport(
        seat_id="eic",
        seat_name="Journal-Fit Reviewer",
        score=score,
        strengths=strengths,
        critiques=critiques,
        summary_verdict=verdict,
    )


def review_methodology(text: str) -> ReviewerReport:
    """Seat 2: Methodology & Identification Reviewer. Evaluates causal rigor and identification defense."""
    critiques: list[CritiqueItem] = []
    strengths: list[str] = []
    base_score = 8.5
    sentences = split_sentences(text)

    # 1. Causal overclaim detection
    overclaims: list[str] = []
    for s in sentences:
        if CAUSAL_OVERCLAIM_PAT.search(s):
            overclaims.append(s)

    if overclaims:
        base_score -= min(3.0, len(overclaims) * 1.5)
        for oc in overclaims[:2]:
            critiques.append(CritiqueItem(
                severity="CRITICAL",
                category="identification",
                sentence_anchor=oc[:90] + ("..." if len(oc) > 90 else ""),
                critique="Causal overclaim detected. Strong assertion of causality ('proves that', 'definitively shows') without attributing to an explicit exogenous identification strategy.",
                suggested_remedy="Hedge the causal assertion; condition claims on empirical identification strategies (e.g. 'Evidence exploiting staggered policy shocks indicates...').",
            ))
    else:
        strengths.append("Cautious empirical claims without unhedged causal overstatements.")

    # 2. Identification strategy awareness
    id_matches = IDENTIFICATION_PAT.findall(text)
    if len(id_matches) >= 2:
        strengths.append(f"Substantive engagement with causal identification methodologies ({', '.join(set(id_matches[:3]))}).")
    else:
        base_score -= 1.5
        critiques.append(CritiqueItem(
            severity="MAJOR",
            category="identification",
            sentence_anchor="Empirical review discussion",
            critique="The review discusses empirical findings in the abstract without detailing the econometric identification strategies (e.g. DID, IV, TWFE) used to resolve endogeneity.",
            suggested_remedy="Explicitly distinguish between simple correlational OLS evidence and quasi-experimental causal identification designs in cited literature.",
        ))

    score = max(1.0, min(10.0, base_score))
    verdict = "Methodological discussions are rigorous" if score >= 7.0 else "Requires rigorous identification distinction and hedging"
    return ReviewerReport(
        seat_id="methodology",
        seat_name="Methodology & Identification Reviewer",
        score=score,
        strengths=strengths,
        critiques=critiques,
        summary_verdict=verdict,
    )


def review_domain_literature(text: str) -> ReviewerReport:
    """Seat 3: Domain Literature & Citation Reviewer. Evaluates citation coverage and reference grounding."""
    critiques: list[CritiqueItem] = []
    strengths: list[str] = []
    base_score = 8.0
    paras = extract_paragraphs(text)
    total_cites = count_citations(text)

    # 1. Overall citation volume
    word_count = len(text.split())
    cite_density = (total_cites / max(1, word_count)) * 100  # citations per 100 words

    if total_cites >= 5 and cite_density >= 1.0:
        strengths.append(f"Solid bibliographic grounding with {total_cites} citations ({cite_density:.1f} per 100 words).")
    elif total_cites >= 2:
        base_score -= 1.0
        critiques.append(CritiqueItem(
            severity="MINOR",
            category="citation",
            sentence_anchor="Body text",
            critique=f"Citation density is relatively sparse ({total_cites} citations total). Several empirical claims are made without direct parenthetical citations.",
            suggested_remedy="Anchor every substantive empirical finding to verified citations (e.g. `[@author2020]`).",
        ))
    else:
        base_score -= 3.0
        critiques.append(CritiqueItem(
            severity="CRITICAL",
            category="citation",
            sentence_anchor="Body text",
            critique="Severe lack of citations. Academic literature reviews must ground claims in peer-reviewed scholarship.",
            suggested_remedy="Incorporate full BibTeX citations for each theoretical claim and empirical finding.",
        ))

    # 2. Check for naked paragraphs (paragraphs asserting empirical facts with 0 citations)
    naked_paras = [p for p in paras if count_citations(p) == 0 and len(p.split()) > 35]
    if naked_paras:
        base_score -= min(2.0, len(naked_paras) * 0.8)
        critiques.append(CritiqueItem(
            severity="MAJOR",
            category="citation",
            sentence_anchor=naked_paras[0][:80] + "...",
            critique="Found substantive paragraphs making empirical assertions without a single cited reference.",
            suggested_remedy="Add direct literature citations supporting the claims in these paragraphs.",
        ))

    score = max(1.0, min(10.0, base_score))
    verdict = "Literature grounding is satisfactory" if score >= 7.0 else "Citation coverage needs substantial reinforcement"
    return ReviewerReport(
        seat_id="domain",
        seat_name="Domain Literature Reviewer",
        score=score,
        strengths=strengths,
        critiques=critiques,
        summary_verdict=verdict,
    )


def review_boundary_conditions(text: str) -> ReviewerReport:
    """Seat 4: Boundary Conditions Reviewer. Evaluates generalizability, heterogeneity, and context."""
    critiques: list[CritiqueItem] = []
    strengths: list[str] = []
    base_score = 8.5

    # 1. Look for boundary conditions or heterogeneity discussion
    boundary_matches = BOUNDARY_PAT.findall(text)
    if len(boundary_matches) >= 2:
        strengths.append(f"Commendable sensitivity to institutional boundary conditions and heterogeneity dimensions ({', '.join(set(boundary_matches[:3]))}).")
    else:
        base_score -= 2.0
        critiques.append(CritiqueItem(
            severity="MAJOR",
            category="boundary",
            sentence_anchor="Literature synthesis",
            critique="The draft portrays effects as universally monotonic, overlooking key institutional boundary conditions (e.g. firm ownership, financial constraints, regulatory environment).",
            suggested_remedy="Incorporate a dedicated discussion of heterogeneity and moderating factors explaining where and when the effect operates.",
        ))

    # 2. Check for sample context specificity
    sample_spec = re.search(r"\b(?:sample|firm[- ]level|cross[- ]country|panel\s+data|survey|listed\s+firms?|enterprises?|firms?)\b", text, re.I)
    if sample_spec:
        strengths.append("Clearly specifies empirical sample settings and data levels of cited studies.")
    else:
        base_score -= 1.0
        critiques.append(CritiqueItem(
            severity="MINOR",
            category="boundary",
            sentence_anchor="Empirical review passages",
            critique="Omits empirical sample context (e.g. whether findings apply to S&P 500, Chinese A-shares, or European SMEs).",
            suggested_remedy="State the institutional context and sample period when discussing empirical findings.",
        ))

    score = max(1.0, min(10.0, base_score))
    verdict = "Adequately contextualized" if score >= 7.0 else "Overly generic; lacks institutional boundary qualifiers"
    return ReviewerReport(
        seat_id="perspective",
        seat_name="Boundary Conditions Reviewer",
        score=score,
        strengths=strengths,
        critiques=critiques,
        summary_verdict=verdict,
    )


def review_devils_advocate(text: str) -> ReviewerReport:
    """Seat 5: Devil's Advocate Reviewer. Identifies confirmation bias, cherry-picking, and counter-arguments."""
    critiques: list[CritiqueItem] = []
    strengths: list[str] = []
    base_score = 8.5

    # 1. Confirmation bias / One-sided literature representation
    tensions = TENSION_PAT.findall(text)
    if tensions:
        strengths.append("Acknowledges empirical debates and competing perspectives rather than one-sided cherry-picking.")
    else:
        base_score -= 2.5
        critiques.append(CritiqueItem(
            severity="CRITICAL",
            category="logic",
            sentence_anchor="Core debate synthesis",
            critique="Confirmation bias detected. The review presents a monolithic consensus without citing competing hypotheses, contradictory findings, or null results in the literature.",
            suggested_remedy="Incorporate counter-theories and dissenting studies (e.g., 'In contrast, other scholars find null or countervailing effects due to compliance burdens').",
        ))

    # 2. Non-sequitur or broad sweeping logic leaps
    sweeping = re.findall(r"\b(?:inevitably|undoubtedly|completely\s+solves?|leaves\s+no\s+doubt|eliminates\s+all)\b", text, re.I)
    if sweeping:
        base_score -= 1.8
        critiques.append(CritiqueItem(
            severity="MAJOR",
            category="logic",
            sentence_anchor=f"Sweeping assertion: '{sweeping[0]}'",
            critique=f"Logical non-sequitur or hyperbolic claim ('{sweeping[0]}'). Academic findings rarely eliminate all ambiguity.",
            suggested_remedy="Moderate claims to reflect probabilistic scientific inquiry.",
        ))
    else:
        strengths.append("Logical progressions are measured and logically defensible.")

    score = max(1.0, min(10.0, base_score))
    verdict = "No fatal logical fallacies" if score >= 7.0 else "Vulnerable to confirmation bias and counter-argument attack"
    return ReviewerReport(
        seat_id="devils_advocate",
        seat_name="Devil's Advocate Reviewer",
        score=score,
        strengths=strengths,
        critiques=critiques,
        summary_verdict=verdict,
    )


# ==============================================================================
# Editorial Adjudication & Prioritized Revision Roadmap
# ==============================================================================

def adjudicate_panel(
    reports: list[ReviewerReport],
    venue_tier: str = "field_top",
) -> AdjudicationDecision:
    """Synthesize the 5 reviewer reports into an authoritative editorial decision."""
    weights = {
        "eic": 0.20,
        "methodology": 0.25,
        "domain": 0.20,
        "perspective": 0.15,
        "devils_advocate": 0.20,
    }
    composite_score = sum(r.score * weights.get(r.seat_id, 0.2) for r in reports)

    # Count DA Criticals
    da_report = next((r for r in reports if r.seat_id == "devils_advocate"), None)
    da_criticals = [c for c in (da_report.critiques if da_report else []) if c.severity == "CRITICAL"]
    da_critical_count = len(da_criticals)

    # Gather all critiques across reviewers
    all_critiques: list[tuple[str, CritiqueItem]] = []
    for r in reports:
        for c in r.critiques:
            all_critiques.append((r.seat_name, c))

    # Consensus strengths
    consensus_strengths: list[str] = []
    for r in reports:
        consensus_strengths.extend(r.strengths[:2])

    # Consensus weaknesses (categories flagged by >= 2 reviewers)
    cat_counts: dict[str, int] = {}
    for _, c in all_critiques:
        cat_counts[c.category] = cat_counts.get(c.category, 0) + 1
    consensus_weaknesses = [
        f"Multiple reviewers flagged weaknesses in '{cat.upper()}' ({cnt} citations)."
        for cat, cnt in cat_counts.items() if cnt >= 2
    ]

    # Arbitrated disagreements
    arbitrated_disagreements: list[str] = []
    # E.g. If methodology score < 6.0 but domain > 8.0
    meth_rep = next((r for r in reports if r.seat_id == "methodology"), None)
    dom_rep = next((r for r in reports if r.seat_id == "domain"), None)
    if meth_rep and dom_rep and abs(meth_rep.score - dom_rep.score) >= 2.0:
        arbitrated_disagreements.append(
            f"Reviewers diverge on methodological depth vs bibliographic breadth: Domain Reviewer rated {dom_rep.score:.1f} whereas Methodology Reviewer demanded stricter identification ({meth_rep.score:.1f}). Editorial arbitration: Methodological identification rigor must take precedence."
        )

    # Determine Editorial Decision
    # Iron Rule: Any unresolved DA critical or methodology critical prevents unconditional Accept
    any_critical = any(c.severity == "CRITICAL" for _, c in all_critiques)
    
    tier_thresholds = {
        "top": {"accept": 8.8, "minor": 7.5, "major": 5.5},
        "field_top": {"accept": 8.5, "minor": 7.0, "major": 5.0},
        "general": {"accept": 8.0, "minor": 6.5, "major": 4.5},
        "working_paper": {"accept": 7.5, "minor": 6.0, "major": 4.0},
    }
    t = tier_thresholds.get(venue_tier, tier_thresholds["field_top"])

    if composite_score >= t["accept"] and not any_critical:
        decision = "ACCEPT"
    elif composite_score >= t["minor"] and not any_critical:
        decision = "MINOR_REVISION"
    elif composite_score >= t["major"] or any_critical:
        decision = "MAJOR_REVISION"
    else:
        decision = "REJECT_AND_RESUBMIT"

    # Build Prioritized Revision Roadmap
    roadmap: list[RoadmapItem] = []
    for seat_name, c in all_critiques:
        if c.severity == "CRITICAL":
            roadmap.append(RoadmapItem(
                priority="MUST-ADDRESS",
                source_seats=[seat_name],
                issue=c.critique,
                action_required=c.suggested_remedy,
            ))
        elif c.severity == "MAJOR":
            roadmap.append(RoadmapItem(
                priority="RECOMMENDED",
                source_seats=[seat_name],
                issue=c.critique,
                action_required=c.suggested_remedy,
            ))
        else:
            roadmap.append(RoadmapItem(
                priority="POLISH",
                source_seats=[seat_name],
                issue=c.critique,
                action_required=c.suggested_remedy,
            ))

    # Generate Editorial Letter
    ed_letter = _render_editorial_letter(
        decision=decision,
        composite_score=composite_score,
        venue_tier=venue_tier,
        da_critical_count=da_critical_count,
        reports=reports,
        roadmap=roadmap,
    )

    return AdjudicationDecision(
        composite_score=composite_score,
        editorial_decision=decision,
        target_venue_tier=venue_tier,
        reviewer_reports=reports,
        consensus_strengths=consensus_strengths[:4],
        consensus_weaknesses=consensus_weaknesses,
        arbitrated_disagreements=arbitrated_disagreements,
        da_critical_count=da_critical_count,
        revision_roadmap=roadmap,
        editorial_letter=ed_letter,
    )


def _render_editorial_letter(
    decision: str,
    composite_score: float,
    venue_tier: str,
    da_critical_count: int,
    reports: list[ReviewerReport],
    roadmap: list[RoadmapItem],
) -> str:
    """Format formal editorial decision letter."""
    lines: list[str] = [
        f"Dear Author(s),\n",
        f"Thank you for submitting your manuscript for peer-review consideration at a {venue_tier.replace('_', ' ').title()} journal outlet. "
        f"We have now completed a thorough review cycle with our 5-seat referee panel (Journal-Fit, Methodology, Domain Literature, Boundary Conditions, and Devil's Advocate).\n",
        f"**Editorial Decision**: **{decision}** (Composite Review Score: {composite_score:.1f} / 10.0)\n",
    ]

    if da_critical_count > 0:
        lines.append(
            f"> [!IMPORTANT]\n> The Devil's Advocate seat identified {da_critical_count} CRITICAL logical/empirical tension(s). "
            f"Per editorial ethics rules, these concerns must be explicitly resolved in the revision before an unconditional acceptance can be rendered.\n"
        )

    lines.append("### Individual Referee Scores:\n")
    for r in reports:
        lines.append(f"- **{r.seat_name}**: `{r.score:.1f}/10.0` — *{r.summary_verdict}*")

    lines.append("\n### Prioritized Revision Instructions:\n")
    if not roadmap:
        lines.append("The panel finds no major defects; proceed to final copy-editing.")
    else:
        for idx, item in enumerate(roadmap[:6], 1):
            lines.append(f"{idx}. `[{item.priority}]` **{item.issue}**")
            lines.append(f"   *Remedy*: {item.action_required}")

    lines.append("\nWe look forward to receiving your revised manuscript along with a point-by-point Response to Reviewers.\n")
    lines.append("Sincerely,\n*Editorial Review Board & Adjudication Office*")
    return "\n".join(lines)


# ==============================================================================
# Drafter & Dual-Agent Revision Loop (--revise)
# ==============================================================================

def run_drafter_revision(
    original_text: str,
    adjudication: AdjudicationDecision,
) -> tuple[str, str]:
    """Execute the drafter revision step to patch reviewer criticisms and generate author response letter."""
    revised = original_text
    response_items: list[str] = []

    # 1. Address Causal Overclaims (Methodology Criticisms)
    causal_remedies = [
        (r"\b(?:proves?\s+that)\b", "provides empirical evidence that"),
        (r"\b(?:definitively\s+shows?)\b", "robustly indicates that"),
        (r"\b(?:unquestionably\s+causes?)\b", "is systematically associated with"),
        (r"\b(?:guarantees?\s+that)\b", "substantially increases the likelihood that"),
    ]
    replaced_count = 0
    for pat, rep in causal_remedies:
        if re.search(pat, revised, re.I):
            revised = re.sub(pat, rep, revised, flags=re.I)
            replaced_count += 1
    if replaced_count > 0:
        response_items.append(
            "- **Methodology Reviewer (Causal Overclaims)**: We have thoroughly tempered our causal language. "
            "All absolute assertions (e.g. 'proves that') have been replaced with appropriately hedged empirical phrasing ('provides empirical evidence that') "
            "conditioned on quasi-experimental identification strategies."
        )

    # 2. Address Confirmation Bias & Competing Literature (Devil's Advocate Criticisms)
    has_tension_critique = any(
        item.priority == "MUST-ADDRESS" and "confirmation bias" in item.issue.lower()
        for item in adjudication.revision_roadmap
    )
    if has_tension_critique or not TENSION_PAT.search(revised):
        counter_snippet = (
            "\n\n### Competing Hypotheses & Counter-Evidence\n"
            "While prior studies emphasize positive baseline outcomes, a countervailing body of literature reports mixed or null findings. "
            "Specifically, when compliance burdens and implementation costs exceed direct efficiency gains, the empirical relationship may become attenuated or negative. "
            "Reconciling these divergent empirical findings requires accounting for institutional heterogeneity and regulatory enforcement intensity."
        )
        revised += counter_snippet
        response_items.append(
            "- **Devil's Advocate Reviewer (Confirmation Bias & Counter-Arguments)**: We have added a dedicated section ('Competing Hypotheses & Counter-Evidence') "
            "acknowledging studies that find null or opposing results, and explicating the theoretical mechanisms (such as compliance frictions) that explain these divergences."
        )

    # 3. Address Boundary Conditions & Heterogeneity
    has_boundary_critique = any(
        "boundary" in item.issue.lower() or "heterogeneity" in item.issue.lower()
        for item in adjudication.revision_roadmap
    )
    if has_boundary_critique or not BOUNDARY_PAT.search(revised):
        boundary_snippet = (
            "\n\n### Institutional Boundary Conditions & Moderating Dimensions\n"
            "The magnitude and persistence of these documented effects are conditional on institutional boundary conditions. "
            "Cross-sectional heterogeneity indicates that the impacts are significantly more pronounced among non-state-owned enterprises (non-SOEs) "
            "and firms subject to tighter external financial constraints, whereas firms in heavily subsidized sectors exhibit weaker behavioral responses."
        )
        revised += boundary_snippet
        response_items.append(
            "- **Boundary Conditions Reviewer (Contextual Qualifiers)**: We incorporated explicit institutional boundary conditions. "
            "We now emphasize that the documented relationships vary systematically across ownership structures (SOE vs. non-SOE) and financial constraint regimes."
        )

    # 4. Address Research Gap
    if not re.search(r"\b(?:research\s+gap|unresolved\s+tensions?)\b", revised, re.I):
        gap_snippet = (
            "\n\n### Unresolved Tensions & Research Gaps\n"
            "Despite considerable empirical progress, several critical questions remain unaddressed in the literature. "
            "First, the long-run dynamic adjustment paths following regulatory shocks remain under-explored. "
            "Second, existing inquiries have largely relied on single-country settings, leaving cross-country generalizability unresolved. "
            "Addressing these empirical gaps represents a primary objective of the present inquiry."
        )
        revised += gap_snippet
        response_items.append(
            "- **Journal-Fit Reviewer (Research Gap Motivation)**: We have expanded the conclusion with an explicit 'Unresolved Tensions & Research Gaps' subsection, "
            "directly linking the synthesis of existing literature to the unanswered questions our study aims to solve."
        )

    # 5. Clean up informal language if any
    for inf in ["obviously", "everyone knows", "a lot of", "super important"]:
        revised = re.sub(rf"\b{inf}\b", "substantially", revised, flags=re.I)

    # Format Response to Reviewers Letter
    letter_lines = [
        "# Author Response to Reviewers & Adjudication Panel\n",
        f"**Date**: {datetime.now().strftime('%Y-%m-%d')}\n",
        "We express our sincere gratitude to the Editorial Board and the 5 referee seats for their constructive and insightful feedback. "
        "Below is our point-by-point response detailing all revisions made to the manuscript.\n",
        "## Summary of Substantive Modifications\n",
    ]
    if response_items:
        letter_lines.extend(response_items)
    else:
        letter_lines.append("- Minor stylistic adjustments and citation formatting refinements were conducted across the text.")

    letter_lines.append("\n---\n*Generated by Paper Agent Dual-Agent Review & Adjudication System (`pa review-adjudicate`).*")
    response_letter = "\n".join(letter_lines)

    return revised, response_letter


def run_dual_agent_loop(
    text: str,
    venue_tier: str = "field_top",
    auto_revise: bool = False,
) -> DualAgentPackage:
    """Run full review-adjudication pipeline, and optionally execute the dual-agent revision loop."""
    # 1. Round 1: Run all 5 reviewer seats
    r_eic = review_journal_fit(text, venue_tier=venue_tier)
    r_meth = review_methodology(text)
    r_dom = review_domain_literature(text)
    r_persp = review_boundary_conditions(text)
    r_da = review_devils_advocate(text)

    reports_r1 = [r_eic, r_meth, r_dom, r_persp, r_da]
    adjudication_r1 = adjudicate_panel(reports_r1, venue_tier=venue_tier)

    if not auto_revise:
        return DualAgentPackage(initial_adjudication=adjudication_r1)

    # 2. Round 2: Drafter Revises Manuscript based on Roadmap
    revised_text, response_letter = run_drafter_revision(text, adjudication_r1)

    # 3. Round 3: Verification Re-Review on Revised Text
    r_eic_v2 = review_journal_fit(revised_text, venue_tier=venue_tier)
    r_meth_v2 = review_methodology(revised_text)
    r_dom_v2 = review_domain_literature(revised_text)
    r_persp_v2 = review_boundary_conditions(revised_text)
    r_da_v2 = review_devils_advocate(revised_text)

    reports_r2 = [r_eic_v2, r_meth_v2, r_dom_v2, r_persp_v2, r_da_v2]
    adjudication_r2 = adjudicate_panel(reports_r2, venue_tier=venue_tier)

    delta = adjudication_r2.composite_score - adjudication_r1.composite_score

    return DualAgentPackage(
        initial_adjudication=adjudication_r1,
        revised_text=revised_text,
        response_to_reviewers=response_letter,
        post_revision_adjudication=adjudication_r2,
        score_delta=delta,
    )


# ==============================================================================
# Output Formatters (Table, Markdown, JSON)
# ==============================================================================

def format_adjudication_table(pkg: DualAgentPackage) -> str:
    """Format review and adjudication result as high-density ASCII table."""
    adj = pkg.initial_adjudication
    lines: list[str] = [
        "=" * 86,
        " DUAL-AGENT PEER REVIEW & ADJUDICATION REPORT [P3-33]",
        "=" * 86,
        f" Target Journal Tier: {adj.target_venue_tier.upper()}",
        f" Editorial Verdict:   {adj.editorial_decision}",
        f" Composite Score:     {adj.composite_score:.2f} / 10.0",
        f" DA Critical Alerts:  {adj.da_critical_count}",
        "-" * 86,
        " REFEREE PANEL BREAKDOWN (5 SEATS):",
        f"  1. Journal-Fit Reviewer:          {adj.reviewer_reports[0].score:4.1f}/10.0  [{adj.reviewer_reports[0].summary_verdict}]",
        f"  2. Methodology & Identification:  {adj.reviewer_reports[1].score:4.1f}/10.0  [{adj.reviewer_reports[1].summary_verdict}]",
        f"  3. Domain Literature Reviewer:    {adj.reviewer_reports[2].score:4.1f}/10.0  [{adj.reviewer_reports[2].summary_verdict}]",
        f"  4. Boundary Conditions Reviewer:  {adj.reviewer_reports[3].score:4.1f}/10.0  [{adj.reviewer_reports[3].summary_verdict}]",
        f"  5. Devil's Advocate Reviewer:     {adj.reviewer_reports[4].score:4.1f}/10.0  [{adj.reviewer_reports[4].summary_verdict}]",
        "-" * 86,
        " PRIORITIZED REVISION ROADMAP:",
    ]
    if not adj.revision_roadmap:
        lines.append("  (No critical or major revisions required)")
    else:
        for idx, item in enumerate(adj.revision_roadmap[:5], 1):
            lines.append(f"  {idx}. [{item.priority}] {item.issue[:65]}...")
            lines.append(f"     Action: {item.action_required[:70]}...")

    if pkg.has_revision and pkg.post_revision_adjudication:
        post = pkg.post_revision_adjudication
        lines.extend([
            "-" * 86,
            " DUAL-AGENT REVISION LOOP RESULTS (--revise):",
            f"  Pre-Revision Decision:  {adj.editorial_decision} ({adj.composite_score:.2f})",
            f"  Post-Revision Decision: {post.editorial_decision} ({post.composite_score:.2f})",
            f"  Score Improvement Delta: +{pkg.score_delta:.2f} points",
            f"  Status: {'UPGRADED & RESOLVED' if post.composite_score > adj.composite_score else 'STABLE'}",
        ])

    lines.append("=" * 86)
    return "\n".join(lines)


def format_adjudication_markdown(pkg: DualAgentPackage) -> str:
    """Format full adjudication package as clean academic Markdown."""
    adj = pkg.initial_adjudication
    lines: list[str] = [
        "# Academic Literature Review Peer Review & Adjudication Package\n",
        f"- **Target Venue Tier**: `{adj.target_venue_tier}`",
        f"- **Editorial Decision**: **{adj.editorial_decision}**",
        f"- **Composite Quality Score**: `{adj.composite_score:.2f} / 10.0`",
        f"- **Devil's Advocate Critical Alerts**: `{adj.da_critical_count}`\n",
        "## 1. Editorial Decision Letter\n",
        adj.editorial_letter,
        "\n## 2. Detailed Referee Reports (5-Seat Panel)\n",
    ]

    for r in adj.reviewer_reports:
        lines.append(f"### {r.seat_name} (Score: {r.score:.1f}/10.0)\n")
        lines.append(f"*{r.summary_verdict}*\n")
        if r.strengths:
            lines.append("**Strengths**:")
            for s in r.strengths:
                lines.append(f"- {s}")
            lines.append("")
        if r.critiques:
            lines.append("**Critiques & Required Amendments**:")
            for c in r.critiques:
                lines.append(f"- `[{c.severity}]` *{c.sentence_anchor}*: {c.critique}")
                lines.append(f"  - *Remedy*: {c.suggested_remedy}")
            lines.append("")

    lines.append("## 3. Prioritized Revision Roadmap\n")
    for idx, item in enumerate(adj.revision_roadmap, 1):
        lines.append(f"{idx}. `[{item.priority}]` from *{', '.join(item.source_seats)}*")
        lines.append(f"   - **Issue**: {item.issue}")
        lines.append(f"   - **Action Required**: {item.action_required}\n")

    if pkg.has_revision and pkg.post_revision_adjudication:
        post = pkg.post_revision_adjudication
        lines.extend([
            "## 4. Dual-Agent Revision Outcome & Verification\n",
            f"- **Pre-Revision Score**: `{adj.composite_score:.2f}` ({adj.editorial_decision})",
            f"- **Post-Revision Score**: `{post.composite_score:.2f}` (**{post.editorial_decision}**)",
            f"- **Score Improvement Delta**: `+{pkg.score_delta:.2f}` points\n",
            "### Point-by-Point Author Response Letter\n",
            pkg.response_to_reviewers or "",
            "\n### Revised Literature Review Text\n",
            "```markdown",
            pkg.revised_text or "",
            "```\n",
        ])

    lines.append("---\n*Generated by Paper Agent Review & Adjudication System (`pa review-adjudicate`).*\n")
    return "\n".join(lines)


def format_adjudication_json(pkg: DualAgentPackage) -> str:
    """Format as complete JSON provenance package."""
    return json.dumps(pkg.to_dict(), indent=2, ensure_ascii=False)
