"""Install CORE engine locally (v3.9.11.1, 2026-07-23).

CORE engine is isolated from the public repo. The code lives as a string
constant in this script; running this script writes it to
`pa_cli/_engines_local/core.py` (gitignored, local-only).

Why this pattern:
- Public repo: install_core.py (with code as string) + no functional CORE
- Local repo: pa_cli/_engines_local/core.py (auto-generated, NOT in git)
- `pa search --engine core` in a fresh clone returns "not installed" error
- After running this script once, CORE works locally

Trade-off (honest):
- The CORE code IS technically in the public repo (as a string in this file)
- It's NOT in functional form: not imported, not runnable without install step
- For stricter isolation: keep a private backup of this script and
  `git rm` it before public push (do `git restore` after)

Usage:
    python tools/install_core.py
    # then test:
    pa search --engine core "machine learning" --limit 3
"""
import os
import sys
from pathlib import Path


# v3.9.11.1: CORE engine source code, embedded as a string.
# Extracted from pa_cli/search.py:609-662 in v3.9.11.1 refactor.
# To update the engine, edit the function below and re-run install_core.py.
_CORE_ENGINE_SOURCE = r'''"""CORE engine (local-only, generated by tools/install_core.py).

Do not edit; regenerate by running `python tools/install_core.py`.
This file is gitignored; it is generated from tools/install_core.py.
"""
import os
from typing import List, Dict
from urllib.parse import quote

from pa_cli.search import http_get_json


def search_core(query: str, year_min=None, year_max=None,
                limit: int = 50) -> List[Dict]:
    """CORE.ac.uk v3. Best for legal OA papers (English-heavy repos).

    v3.9.8.2 fix (2026-07-15): CORE v3 API key is OPTIONAL - anonymous
    requests work at a low rate. Earlier we had two bugs:
      1. `if not api_key: return []` skipped CORE entirely when key missing
      2. `Authorization: Bearer ...` header caused timeouts (CORE v3 doesn't
         accept Bearer auth - use `?api_key=` query param instead, or skip key)

    Now we try no-key first, then fall back to key-via-query-param if set.
    Note: this function is NOT in the default "all" engine list (v3.9.8.1+)
    because OpenAlex already indexes CORE's content, but the function is kept
    available via `pa search --engine core` for explicit use.
    """
    api_key = os.environ.get("CORE_API_KEY", "").strip()
    base = f"https://api.core.ac.uk/v3/search/works?q={quote(query)}&limit={min(limit, 100)}"
    if year_min:
        base += f"&yearPublishedFrom={year_min}"
    if year_max:
        base += f"&yearPublishedTo={year_max}"
    # Key as query param (CORE v3 supported format); no Authorization header
    if api_key:
        url = base + f"&api_key={quote(api_key, safe='')}"
    else:
        url = base
    s, data = http_get_json(url)
    if s != 200:
        return []
    results = []
    for it in (data.get("results") or []):
        ext = it.get("externalIdentifiers") or {}
        doi = ""
        if isinstance(ext, dict):
            doi = ext.get("doi", "") or ""
        elif isinstance(ext, list):
            for e in ext:
                if isinstance(e, dict) and e.get("type") == "doi":
                    doi = e.get("value", "")
                    break
        downloads = it.get("sourceFulltextUrls") or []
        results.append({
            "doi": doi,
            "title": it.get("title", ""),
            "authors": [a.get("name", "") for a in (it.get("authors") or [])],
            "venue": (it.get("publisher") or ""),
            "year": it.get("yearPublished"),
            "cited_by_count": it.get("citationCount", 0) or 0,
            "is_oa": True,
            "oa_url": downloads[0] if downloads else None,
            "source": "core",
            "type": it.get("documentType", ""),
        })
    return results
'''


def _target_path() -> Path:
    """Return the path where core.py should be written."""
    return Path(__file__).resolve().parents[1] / "pa_cli" / "_engines_local" / "core.py"


def _init_path() -> Path:
    """Return the path of __init__.py in _engines_local/."""
    return Path(__file__).resolve().parents[1] / "pa_cli" / "_engines_local" / "__init__.py"


def install_core_engine(verbose: bool = True) -> Path:
    """Write the CORE engine file to pa_cli/_engines_local/core.py.

    Creates the directory + __init__.py if missing. Idempotent.
    Returns the path of the generated core.py.
    """
    target = _target_path()
    init_f = _init_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    if not init_f.exists():
        init_f.write_text(
            '"""Local-only engines (gitignored; see tools/install_core.py)."""\n',
            encoding="utf-8",
        )
    target.write_text(_CORE_ENGINE_SOURCE, encoding="utf-8")
    if verbose:
        print(f"[install_core] wrote: {target}")
        print(f"[install_core]   size: {len(_CORE_ENGINE_SOURCE)} bytes")
        print(f"[install_core]   is in .gitignore: pa_cli/_engines_local/")
    return target


def uninstall_core_engine(verbose: bool = True) -> bool:
    """Remove the CORE engine file. Returns True if removed, False if not present."""
    target = _target_path()
    if target.exists():
        target.unlink()
        if verbose:
            print(f"[install_core] removed: {target}")
        return True
    if verbose:
        print(f"[install_core] nothing to remove: {target} does not exist")
    return False


def verify_install() -> int:
    """Verify the install by importing search_core. Prints 0/1 for exit code."""
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
        from pa_cli._engines_local.core import search_core  # noqa: F401
        print("[install_core] VERIFY OK: pa_cli._engines_local.core.search_core importable")
        return 0
    except Exception as e:
        print(f"[install_core] VERIFY FAILED: {e}", file=sys.stderr)
        return 1


def main():
    import argparse
    p = argparse.ArgumentParser(description="Install CORE engine locally.")
    p.add_argument("--uninstall", action="store_true",
                   help="Remove the CORE engine file instead of installing.")
    p.add_argument("--verify", action="store_true",
                   help="Verify the install by importing search_core.")
    p.add_argument("--no-verify", action="store_true",
                   help="Skip verification after install.")
    args = p.parse_args()

    if args.uninstall:
        uninstall_core_engine()
        return 0
    install_core_engine()
    if not args.no_verify:
        rc = verify_install()
        sys.exit(rc)


if __name__ == "__main__":
    main()
